"""make regulatory_mapping.control_key unique

Revision ID: 152864ab753e
Revises: c7e9f572232b
Create Date: 2026-07-16 22:40:31.760797

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '152864ab753e'
down_revision: Union[str, Sequence[str], None] = 'c7e9f572232b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_mapping_control_key'), table_name='regulatory_mapping')
    op.create_index(op.f('ix_regulatory_mapping_control_key'), 'regulatory_mapping', ['control_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_mapping_control_key'), table_name='regulatory_mapping')
    op.create_index(op.f('ix_regulatory_mapping_control_key'), 'regulatory_mapping', ['control_key'], unique=False)
    # ### end Alembic commands ###
