"""initial schema

Revision ID: b56c60c753bc
Revises: 
Create Date: 2026-07-16 21:53:11.341422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56c60c753bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_function', sa.Enum('Loan Underwriting', 'Fraud Detection', 'Collections', 'Customer Service', 'Document Processing', 'Risk Analytics', name='businessfunction', native_enum=False), nullable=False),
    sa.Column('model_type', sa.Enum('Machine Learning', 'Deep Learning', 'Generative AI', 'Rule Based Engine', 'Third Party AI API', name='modeltype', native_enum=False), nullable=False),
    sa.Column('deployment_stage', sa.Enum('Development', 'Testing', 'Production', 'Retired', name='deploymentstage', native_enum=False), nullable=False),
    sa.Column('business_owner', sa.String(), nullable=False),
    sa.Column('risk_owner', sa.String(), nullable=False),
    sa.Column('technical_owner', sa.String(), nullable=False),
    sa.Column('data_classification', sa.Enum('Public', 'Internal', 'Confidential', 'Restricted', name='dataclassification', native_enum=False), nullable=False),
    sa.Column('vendor_dependency', sa.Enum('Internal', 'External Vendor', name='vendordependency', native_enum=False), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model_name', sa.String(), nullable=True),
    sa.Column('has_documentation', sa.Boolean(), nullable=False),
    sa.Column('has_independent_validation', sa.Boolean(), nullable=False),
    sa.Column('has_explainability', sa.Boolean(), nullable=False),
    sa.Column('has_drift_monitoring', sa.Boolean(), nullable=False),
    sa.Column('has_human_override', sa.Boolean(), nullable=False),
    sa.Column('has_audit_logging', sa.Boolean(), nullable=False),
    sa.Column('has_deployment_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('llm_provider_used', sa.String(), nullable=True),
    sa.Column('guardrail_result', sa.String(), nullable=True),
    sa.Column('risk_assessment_result', sa.String(), nullable=True),
    sa.Column('report_generated', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('guardrail_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('INPUT', 'PROCESSING', 'OUTPUT', name='guardrailstage', native_enum=False), nullable=False),
    sa.Column('detector', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'MASK', 'WARNING', 'BLOCK', name='guardrailaction', native_enum=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('api_credential_ref', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_key', sa.String(), nullable=False),
    sa.Column('regulation_name', sa.String(), nullable=False),
    sa.Column('reference_text', sa.Text(), nullable=False),
    sa.Column('guidance_type', sa.Enum('BINDING', 'EMERGING', name='guidancetype', native_enum=False), nullable=False),
    sa.Column('effective_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_mapping_control_key'), 'regulatory_mapping', ['control_key'], unique=False)
    op.create_table('ai_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NOT_REGISTERED', 'REGISTERED', name='assetstatus', native_enum=False), nullable=False),
    sa.Column('linked_model_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='riskcategory', native_enum=False), nullable=False),
    sa.Column('controls_required', sa.Integer(), nullable=False),
    sa.Column('controls_passed', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity', native_enum=False), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('regulatory_reference', sa.String(), nullable=True),
    sa.Column('control_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REMEDIATION', 'CLOSED', name='findingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('JSON', 'PDF', name='reporttype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='riskcategory', native_enum=False), nullable=False),
    sa.Column('assessment_reason', sa.Text(), nullable=False),
    sa.Column('factor_breakdown', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediation_actions')
    op.drop_table('risk_assessments')
    op.drop_table('reports')
    op.drop_table('findings')
    op.drop_table('control_assessments')
    op.drop_table('ai_assets')
    op.drop_index(op.f('ix_regulatory_mapping_control_key'), table_name='regulatory_mapping')
    op.drop_table('regulatory_mapping')
    op.drop_table('llm_configurations')
    op.drop_table('guardrail_policies')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
